language: node_js
node_js:
  - "6.9"
  
install:
  - npm install
  
script:
  - npm run build
  
deploy:
  provider: gcs
  access_key_id: "$ACCESS_ID"
  secret_access_key: "$ACCESS_KEY"
  bucket: "$BUCKET_NAME"
  skip_cleanup: true
  acl: public-read
  local-dir: dist
